kind: Namespace
apiVersion: v1
metadata:
  name: captain-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: captain
subjects:
  - kind: ServiceAccount
    name: default
    namespace: captain-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
