apiVersion: app.alauda.io/v1alpha1
kind: HelmRequest
metadata:
  name: zookeeper
  namespace: captain-system
spec:
  chart: silk-road/zookeeper
  namespace: captain-system
  releaseName: zookeeper
  version: 3.9.1
  values:
    global:
      storageClass: ""
    # auth:
    #   client:
    #     enabled: true
    #     clientUser: root
    #     clientPassword: zookeeper
    replicaCount: 1
    resources:
      requests:
        cpu: 0.5
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
    persistence:
      enabled: false
      size: 1Gi
    metrics:
      enabled: false
    tls:
      client:
        enabled: false
