apiVersion: app.alauda.io/v1alpha1
kind: HelmRequest
metadata:
  name: prometheus
  namespace: captain-system
spec:
  chart: silk-road/prometheus
  namespace: captain-system
  releaseName: prometheus
  version: 0.68.0
  values:
    global:
      storageClass: ""
    operator:
      enabled: false
    prometheus:
      enabled: true
      service:
        ports:
          http: 9090
      # metric保存时长
      retention: 10d
      replicaCount: 1
      shards: 1
      persistence:
        enabled: false
        size: 1Gi
    alertmanager:
      enabled: true
      retention: 10d
      persistence:
        enabled: false
        size: 1Gi
