apiVersion: app.alauda.io/v1alpha1
kind: HelmRequest
metadata:
  name: grafana
  namespace: captain-system
spec:
  chart: silkraod/grafana
  namespace: captain-system
  releaseName: grafana
  version: 10.2.0
  values:
    global:
      storageClass: ""
    admin:
      user: root
      password: grafana
    grafana:
      replicaCount: 1
      resources:
        requests:
          cpu: 0.5
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
      affinity: {}
      nodeSelector: {}
      tolerations: []
    persistence:
      # 测试环境不开启
      enabled: false
      size: 1Gi
    service:
      ports:
        grafana: 3000
    metrics:
      enabled: false
