apiVersion: app.alauda.io/v1alpha1
kind: HelmRequest
metadata:
  name: redis-cluster
  namespace: captain-system
spec:
  chart: silk-road/redis-cluster
  namespace: captain-system
  releaseName: redis-cluster
  version: 7.2.3
  values:
    global:
      redis:
        password: lovecy520824.
        storageClass: ""
    service:
      ports:
        redis: 6379
    persistence:
      enabled: false
      size: 1Gi
    redis:
      resources:
        requests:
          cpu: 500m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
    cluster:
      nodes: 6
      replicas: 1
    metrics:
      enabled: false
